version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
     - '8080:8080'
     depends_on:
        - neo4j
        - redis
  cli:
    build: .
     depends_on:
        - neo4j
        - redis
  neo4j:
    image: 'neo4j:latest'
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=none
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'